- name: add_user_to_docker_group
  user:
    name: "{{ansible_user_id}}"
    groups: docker
    append: yes
  become: yes

- name: start_docker_daemon
  service:
    name: docker
    state: started
  become: yes