---
- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-keyring.asc
  become: yes

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-keyring.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present
  become: yes

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes
  notify: 
    - add_user_to_docker_group
    - start_docker_daemon
  become: yes
