---
- hosts: localhost
  gather_facts: true
  become: no
  roles:
    - { role: common, tags: ["Common"] }
    - { role: intel-driver, tags: ["Intel Driver"] }
    - { role: docker, tags: ["Docker"] }
    - { role: ros2, tags: ["ROS2"] }
    - { role: nvidia-driver, tags: ["NVIDIA Driver"] }
    - { role: nvidia-machine-learning, tags: ["NVIDIA Machine Learning"] }
    - { role: nvidia-docker, tags: ["NVIDIA Docker"] }

